version: '3'

env:
  ROOT_TOKEN: "I5gVSOrW5Fb4G+2iRMcFkj3+cSuWrBB+foUcXZzGhkI="
  JWT_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzeXMvdXNlcnMvdXNlcjEiLCJleHAiOjIwNjMxMjEzMTAsImlhdCI6MTc0Nzc2MTMxMCwiU2lkIjoiODkwMjBiNDMtYzhmOC00NDA1LThiYjEtM2EzMmI5NDU0NjJiIn0.QWrsCh6O0Jx6RPW0hSOAJkzjmyGG1D-milkRELRTjOs'

tasks:
  status:
    cmd: curl http://127.0.0.1:8080/api/sys/status

  init:
    cmd: curl -v -X POST http://127.0.0.1:8080/api/sys/init

  unseal:
    cmd: 'curl -v -X POST -d "{\"key\": \"$ROOT_TOKEN\"}" -H "X-Secman-Token: $ROOT_TOKEN" http://127.0.0.1:8080/api/sys/unseal | jq'

  enable-*:
    vars:
      ENGINE: '{{index .MATCH 0}}'
    cmds:
      - 'curl -v -X POST -H "X-Secman-Token: $ROOT_TOKEN" http://127.0.0.1:8080/api/sys/enable/{{.ENGINE}} -d "{}" | jq'

  auth-params:
    cmds:
      - 'curl -H "Authorization: Bearer $JWT_TOKEN" -v http://127.0.0.1:8080/api/engine/auth/logopass/ | jq'

  enable_auth-*:
    vars:
      ENGINE: '{{index .MATCH 0}}'
    cmds:
      - 'curl -v -X POST -H "X-Secman-Token: $ROOT_TOKEN" http://127.0.0.1:8080/api/sys/auth/enable -d "{\"engine_path\": \"{{.ENGINE}}\"}" | jq'

  login:
    cmds:
      - "curl -v -X POST -d '{\"login\": \"user1\", \"password\": \"qwerty$4\"}'  http://127.0.0.1:8080/api/engine/auth/logopass/login| jq"

  register:
    cmds:
      - "curl -v -X POST -d '{\"login\": \"user1\", \"password\": \"qwerty$4\"}'  http://127.0.0.1:8080/api/engine/auth/logopass/register| jq"

  run:
    cmds:
      - go build cmd/server/main.go
      - mv main secman
      - ./secman

  genmock-*:
    desc: exec "task genmock-OrdersRepository -- internal/server/entities"
          then rename internal/server/entities/mocks/CreateOrderService to snake case
    vars:
      STRUCT: '{{index .MATCH 0}}'
    cmds:
      - mockgen -package=mocks -destination=pkg/mocks/{{.CLI_ARGS}}/{{.STRUCT}}.go github.com/vysogota0399/secman/{{.CLI_ARGS}} {{.STRUCT}}