// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/secman/internal/secman (interfaces: ILogicalStorage)

// Package mocks is a generated GoMock package.
package secman

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockILogicalStorage is a mock of ILogicalStorage interface.
type MockILogicalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockILogicalStorageMockRecorder
}

// MockILogicalStorageMockRecorder is the mock recorder for MockILogicalStorage.
type MockILogicalStorageMockRecorder struct {
	mock *MockILogicalStorage
}

// NewMockILogicalStorage creates a new mock instance.
func NewMockILogicalStorage(ctrl *gomock.Controller) *MockILogicalStorage {
	mock := &MockILogicalStorage{ctrl: ctrl}
	mock.recorder = &MockILogicalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogicalStorage) EXPECT() *MockILogicalStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockILogicalStorage) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockILogicalStorageMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockILogicalStorage)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockILogicalStorage) Get(arg0 context.Context, arg1 string) (Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockILogicalStorageMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockILogicalStorage)(nil).Get), arg0, arg1)
}

// GetOk mocks base method.
func (m *MockILogicalStorage) GetOk(arg0 context.Context, arg1 string) (Entry, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOk", arg0, arg1)
	ret0, _ := ret[0].(Entry)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOk indicates an expected call of GetOk.
func (mr *MockILogicalStorageMockRecorder) GetOk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOk", reflect.TypeOf((*MockILogicalStorage)(nil).GetOk), arg0, arg1)
}

// List mocks base method.
func (m *MockILogicalStorage) List(arg0 context.Context, arg1 string) ([]Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockILogicalStorageMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockILogicalStorage)(nil).List), arg0, arg1)
}

// Prefix mocks base method.
func (m *MockILogicalStorage) Prefix() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prefix")
	ret0, _ := ret[0].(string)
	return ret0
}

// Prefix indicates an expected call of Prefix.
func (mr *MockILogicalStorageMockRecorder) Prefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prefix", reflect.TypeOf((*MockILogicalStorage)(nil).Prefix))
}

// Update mocks base method.
func (m *MockILogicalStorage) Update(arg0 context.Context, arg1 string, arg2 Entry, arg3 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockILogicalStorageMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockILogicalStorage)(nil).Update), arg0, arg1, arg2, arg3)
}
