// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vysogota0399/secman/internal/secman (interfaces: BarrierStorage)

// Package mocks is a generated GoMock package.
package secman

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"

)

// MockBarrierStorage is a mock of BarrierStorage interface.
type MockBarrierStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBarrierStorageMockRecorder
}

// MockBarrierStorageMockRecorder is the mock recorder for MockBarrierStorage.
type MockBarrierStorageMockRecorder struct {
	mock *MockBarrierStorage
}

// NewMockBarrierStorage creates a new mock instance.
func NewMockBarrierStorage(ctrl *gomock.Controller) *MockBarrierStorage {
	mock := &MockBarrierStorage{ctrl: ctrl}
	mock.recorder = &MockBarrierStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBarrierStorage) EXPECT() *MockBarrierStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBarrierStorage) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBarrierStorageMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBarrierStorage)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockBarrierStorage) Get(arg0 context.Context, arg1 string) (Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBarrierStorageMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBarrierStorage)(nil).Get), arg0, arg1)
}

// GetOk mocks base method.
func (m *MockBarrierStorage) GetOk(arg0 context.Context, arg1 string) (Entry, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOk", arg0, arg1)
	ret0, _ := ret[0].(Entry)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetOk indicates an expected call of GetOk.
func (mr *MockBarrierStorageMockRecorder) GetOk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOk", reflect.TypeOf((*MockBarrierStorage)(nil).GetOk), arg0, arg1)
}

// List mocks base method.
func (m *MockBarrierStorage) List(arg0 context.Context, arg1 string) ([]Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBarrierStorageMockRecorder) List(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBarrierStorage)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockBarrierStorage) Update(arg0 context.Context, arg1 string, arg2 Entry, arg3 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBarrierStorageMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBarrierStorage)(nil).Update), arg0, arg1, arg2, arg3)
}
